#!/bin/bash

SAMPLES=13720


for var in 0 .025 .05 .1 .15 .25 .4
do
    echo "mean prob" > output
    for u in {0..400};
    do  
	num=$( eval calc $u/200 );
	echo $num,$var
	pow $SAMPLES $num $var | tail -1 | awk -F' ' '{print $3}' | sed "s/^/$num\t/"  >> output;
    done
    cp output ../../light/cc/fail$var.dat
done